<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ Root Word Method Drill</title>
  <style>
    /* ... (previous styles) ... */

    /* Make sure the intro text is initially hidden */
    .intro-text {
      display: none;
    }
  </style>
</head>
<body>
  <h1>ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ Root Word Method Drill</h1>
  <label for="showHideIntro">
    <input type="checkbox" id="showHideIntro"> Show/Hide Intro
  </label>
  <div class="intro-text">
    <p>Welcome to the Root Word Method drill! This drill is intended to help you work on conjugating verbs and, optionally, adding affixes.<br>
    You're responsible for checking your own work! Please rely on materials generated by first-language speakers.<br>
    As you're working, don't forget your root suffixes, and be sure to consider whether your verb needs a Set A or Set B pronoun.<br>
    This drill is quite open-ended -- don't be discouraged! A great way to use it is to try and write a Cherokee sentence around the word<br>
    that is randomly generated for you.</p>
  </div>

  <!-- ... (rest of the HTML) ... -->

  <script>
    // ... (previous script) ...

    // Function to show or hide the intro text
    const introCheckbox = document.getElementById("showHideIntro");
    const introText = document.querySelector(".intro-text");

    introCheckbox.addEventListener("change", () => {
      if (introCheckbox.checked) {
        introText.style.display = "block";
      } else {
        introText.style.display = "none";
      }
    });

    // Update button styles for mobile-friendly layout
    const buttons = document.querySelectorAll("button");
    buttons.forEach((button) => {
      button.style.width = "100%"; // Make buttons span the full width
    });

    // Update canvas size for mobile-friendly layout
    function updateCanvasSize() {
      const canvases = document.querySelectorAll("canvas");
      canvases.forEach((canvas) => {
        const boxWidth = canvas.parentElement.clientWidth;
        canvas.width = boxWidth;
        canvas.height = boxWidth / 3; // You can adjust the aspect ratio as needed
      });
    }

    function getTextHeight(fontSize) {
      const testCanvas = document.createElement("canvas");
      const testCtx = testCanvas.getContext("2d");
      testCtx.font = `${fontSize}px Arial`;
      return testCtx.measureText("M").actualBoundingBoxAscent + testCtx.measureText("M").actualBoundingBoxDescent;
    }

    function adjustBoxHeights() {
      const container = document.querySelector(".container");
      const boxes = document.querySelectorAll(".box");
      const totalBoxMargin = 16; // 8px top margin + 8px bottom margin per box
      const availableHeight = window.innerHeight - container.offsetTop - totalBoxMargin;

      const numBoxes = boxes.length;
      const fontSize = 24; // Adjust the font size if needed
      const textHeight = getTextHeight(fontSize);
      const boxHeight = Math.floor(textHeight * 1.5); // Set canvas height to 150% of text height

      boxes.forEach(box => {
        box.style.height = `${boxHeight}px`;
      });
    }

    // Call the updateCanvasSize function when the page loads and on window resize
    window.addEventListener("load", () => {
      updateCanvasSize();
      adjustBoxHeights();
      generateRandomWord(); // Generate random words on initial load
    });

    window.addEventListener("resize", () => {
      updateCanvasSize();
      adjustBoxHeights();
    });
  </script>
</body>
</html>
