<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ Root Word Method Drill</title>
  <style>
    /* ... (previous styles) ... */

    /* Make sure the intro text is initially hidden */
    .intro-text {
      display: none;
    }
  </style>
</head>
<body>
  <h1>ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ Root Word Method Drill</h1>
  <label for="showHideIntro">
    <input type="checkbox" id="showHideIntro"> Show/Hide Intro
  </label>
  <div class="intro-text">
    <p>Welcome to the Root Word Method drill! This drill is intended to help you work on conjugating verbs and, optionally, adding affixes.<br>
    You're responsible for checking your own work! Please rely on materials generated by first-language speakers.<br>
    As you're working, don't forget your root suffixes, and be sure to consider whether your verb needs a Set A or Set B pronoun.<br>
    This drill is quite open-ended -- don't be discouraged! A great way to use it is to try and write a Cherokee sentence around the word<br>
    that is randomly generated for you.</p>
  </div>

  <!-- ... (rest of the HTML) ... -->

  <script>

    // Function to show or hide the intro text
    const introCheckbox = document.getElementById("showHideIntro");
    const introText = document.querySelector(".intro-text");

    introCheckbox.addEventListener("change", () => {
      if (introCheckbox.checked) {
        introText.style.display = "block";
      } else {
        introText.style.display = "none";
      }
    });

  
  </script>
</body>
</html>
